__title__ = "DataHorse"
__description__ = "Do data science and data analysis in plain english"
__version__ = "0.0.0"
__author__ = "DeDolphins"
__author_email__ = "info@datahorse.ai"
__license__ = "creativeml-openrail-m"
__url__ = "https://datahorse.ai"